// <auto-generated />
using BakingPrecision.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BakingPrecision.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260514232223_SeedInitialCulinaData")]
    partial class SeedInitialCulinaData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("BakingPrecision.API.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngredientCategoryId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientCategoryId = 1,
                            Name = "All-Purpose Flour"
                        },
                        new
                        {
                            Id = 2,
                            IngredientCategoryId = 2,
                            Name = "Granulated Sugar"
                        },
                        new
                        {
                            Id = 3,
                            IngredientCategoryId = 3,
                            Name = "Unsalted Butter"
                        },
                        new
                        {
                            Id = 4,
                            IngredientCategoryId = 4,
                            Name = "Large Egg"
                        },
                        new
                        {
                            Id = 5,
                            IngredientCategoryId = 6,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 6,
                            IngredientCategoryId = 4,
                            Name = "Whole Milk"
                        },
                        new
                        {
                            Id = 7,
                            IngredientCategoryId = 7,
                            Name = "Table Salt"
                        },
                        new
                        {
                            Id = 8,
                            IngredientCategoryId = 5,
                            Name = "Baking Soda"
                        },
                        new
                        {
                            Id = 9,
                            IngredientCategoryId = 5,
                            Name = "Baking Powder"
                        },
                        new
                        {
                            Id = 10,
                            IngredientCategoryId = 2,
                            Name = "Brown Sugar"
                        });
                });

            modelBuilder.Entity("BakingPrecision.API.Models.IngredientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IngredientCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flours"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sugars"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fats"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dairy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Leaveners"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Liquids"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spices"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BakingPrecision.API.Models.IngredientConversion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GramsPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("UnitId");

                    b.ToTable("IngredientConversions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GramsPerUnit = 120.0m,
                            IngredientId = 1,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 2,
                            GramsPerUnit = 200.0m,
                            IngredientId = 2,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 3,
                            GramsPerUnit = 227.0m,
                            IngredientId = 3,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 4,
                            GramsPerUnit = 236.0m,
                            IngredientId = 5,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 5,
                            GramsPerUnit = 240.0m,
                            IngredientId = 6,
                            UnitId = 4
                        },
                        new
                        {
                            Id = 6,
                            GramsPerUnit = 6.0m,
                            IngredientId = 7,
                            UnitId = 5
                        },
                        new
                        {
                            Id = 7,
                            GramsPerUnit = 6.0m,
                            IngredientId = 8,
                            UnitId = 5
                        },
                        new
                        {
                            Id = 8,
                            GramsPerUnit = 4.0m,
                            IngredientId = 9,
                            UnitId = 5
                        },
                        new
                        {
                            Id = 9,
                            GramsPerUnit = 213.0m,
                            IngredientId = 10,
                            UnitId = 4
                        });
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId")
                        .IsUnique();

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yield")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GramWeight")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UnitId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.RecipeStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StepNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "g",
                            Name = "Gram",
                            System = "Metric"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "kg",
                            Name = "Kilogram",
                            System = "Metric"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "ml",
                            Name = "Milliliter",
                            System = "Metric"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "cup",
                            Name = "Cup",
                            System = "US Customary"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "tsp",
                            Name = "Teaspoon",
                            System = "US Customary"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "tbsp",
                            Name = "Tablespoon",
                            System = "US Customary"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "unit",
                            Name = "Unit",
                            System = "Metric"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "oz",
                            Name = "Ounce",
                            System = "US Customary"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "lb",
                            Name = "Pound",
                            System = "US Customary"
                        });
                });

            modelBuilder.Entity("BakingPrecision.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Ingredient", b =>
                {
                    b.HasOne("BakingPrecision.API.Models.IngredientCategory", "Category")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.IngredientConversion", b =>
                {
                    b.HasOne("BakingPrecision.API.Models.Ingredient", "Ingredient")
                        .WithMany("Conversions")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakingPrecision.API.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Media", b =>
                {
                    b.HasOne("BakingPrecision.API.Models.Recipe", "Recipe")
                        .WithOne("Media")
                        .HasForeignKey("BakingPrecision.API.Models.Media", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Recipe", b =>
                {
                    b.HasOne("BakingPrecision.API.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.RecipeIngredient", b =>
                {
                    b.HasOne("BakingPrecision.API.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakingPrecision.API.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BakingPrecision.API.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.RecipeStep", b =>
                {
                    b.HasOne("BakingPrecision.API.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Ingredient", b =>
                {
                    b.Navigation("Conversions");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.IngredientCategory", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.Recipe", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("RecipeIngredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("BakingPrecision.API.Models.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
